version: '3'
services:
    certbot:
        build: ./
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./log:/var/log
        environment:
            API_KEY: 
            API_TOKEN: 
        command: certonly -d $DOMAIN --manual -n --agree-tos --email $EMAIL --manual-public-ip-logging-ok --preferred-challenges dns --manual-auth-hook "/root/au/au.sh python godaddy add" --manual-cleanup-hook "/root/au/au.sh python godaddy clean"

